name: Build Pull Request

on:
  pull_request: {}

jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: danielswensson/auto-assign-owner-action@v1
        if: ${{ github.head_ref == 'feat/update-icons' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: ${{ github.head_ref == 'feat/update-icons' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/Decathlon/projects/3
          GITHUB_PROJECT_COLUMN_NAME: 👀 Dev review

      - name: Restore/create node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build sources
        run: yarn build

      - name: Build showcases
        run: yarn build-storybook
